# Generated by Django 3.2.9 on 2021-11-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_auto_20211115_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='src',
            field=models.TextField(default=''),
        ),
    ]
