# Generated by Django 3.2.9 on 2021-11-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_snack_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='src',
        ),
    ]
